services:
  php-apache:
    build: .
    container_name: php-apache-new
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db-new
    environment:
      MYSQL_ROOT_PASSWORD: thet
      MYSQL_DATABASE: school
    # volumes:
    #   - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

# volumes:
#   db_data:
